BudgetAnalysisWeb/BudgetAnalysisWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', TemplateView.as_view(template_name='users/registration/home.html'), name='home'),
]

BudgetAnalysisWeb/users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from users.views import *

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', MyLoginView.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),

    path('confirm_email/',
         TemplateView.as_view(template_name='users/registration/confirm_email.html'),
         name='confirm_email'),

    path('verify_email/<uidb64>/<token>/',
         EmailVerify.as_view(),
         name='verify_email'),

    path('invalid_verify/',
         TemplateView.as_view(template_name='users/registration/invalid_verify.html'),
         name='invalid_verify'),

    path('', main, name='main'),
    path('profile/', profile_view, name='profile'),

    path('categories/', category_list, name='category_list'),
    path('categories/create/', category_create, name='category_create'),
    path('categories/<int:category_id>/edit/', category_edit, name='category_edit'),
    path('categories/<int:category_id>/delete/', category_delete, name='category_delete'),

    path('accounts/', account_list, name='accounts'),
    path('accounts/create/', create_account, name='create_account'),
    path('accounts/<int:account_id>/edit/', edit_account, name='edit_account'),
    path('accounts/delete/<int:account_id>/', delete_account, name='delete_account'),

    path('transfer/', transfer, name='transfer'),

    path('adding/add-operation/', add_operation, name='add_operation'),
    path('adding/edit-operation/<int:operation_id>/', edit_operation, name='edit_operation'),
    path('adding/delete-operation/<int:operation_id>/', delete_operation, name='delete_operation'),
    path('adding/operation-list/', operation_list, name='operation_list'),

    path('adding/add-transaction/', add_regular_transaction, name='add_transaction'),
    path('adding/edit-transaction/<int:transaction_id>/', edit_regular_transaction, name='edit_transaction'),
    path('adding/delete-transaction/<int:transaction_id>/', delete_regular_transaction, name='delete_transaction'),
    path('adding/transaction-list/', regular_transaction_list, name='transaction_list'),

    path('adding/', main_page_for_adding_operation, name='main_for_adding'),

    path('statistics/', statistics_page, name='statistics'),
]

BudgetAnalysisWeb/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save

from BudgetAnalysisWeb.settings import AUTH_USER_MODEL
from users.validators import positive_number_validator


class User(AbstractUser):
    email = models.EmailField(
        _('email address'),
        unique=True,
    )

    email_verify = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class UserDataModel(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    surname = models.CharField(max_length=100, blank=True)
    patronymic = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True)
    sex = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return f"{self.name}: {self.user}"


class CategoryModel(models.Model):
    EXPENSES = 'Расходы'
    INCOME = 'Доходы'
    CATEGORY_TYPE_CHOICES = (
        (EXPENSES, 'Расходы'),
        (INCOME, 'Доходы'),
    )
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=100, blank=True)
    key = models.CharField(max_length=100, choices=CATEGORY_TYPE_CHOICES, default=EXPENSES, blank=True)
    color = models.CharField(max_length=7, default="#000000")

    def __str__(self):
        return f"{self.category_name}"


class Account(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    balance = models.DecimalField(max_digits=10, decimal_places=2, validators=[positive_number_validator])
    color = models.CharField(max_length=7, default="#000000")

    def __str__(self):
        return f"{self.name}"


class Transaction(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    from_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='sent_transactions')
    to_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='received_transactions')
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[positive_number_validator])
    date = models.DateField(default=timezone.now, editable=True)
    comment = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.from_account} -> {self.to_account}: {self.amount}"


class Operation(models.Model):
    EXPENSES = 'Расходы'
    INCOME = 'Доходы'
    CATEGORY_TYPE_CHOICES = (
        (EXPENSES, 'Расходы'),
        (INCOME, 'Доходы'),
    )

    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    key = models.CharField(max_length=100, choices=CATEGORY_TYPE_CHOICES, default=EXPENSES, blank=True)
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[positive_number_validator])
    date = models.DateField()
    comment = models.TextField(blank=True)

    def __str__(self):
        return f"{self.key}, {self.category}, {self.amount}, " \
               f"{self.account}, {self.date}, {self.comment}"

    def save(self, *args, **kwargs):
        if self.key == Operation.EXPENSES and self.amount > self.account.balance:
            raise ValidationError("Сумма расхода превышает баланс счета.")

        super().save(*args, **kwargs)

        if self.key == Operation.EXPENSES:
            self.account.balance -= self.amount
            self.account.save()

        elif self.key == Operation.INCOME:
            self.account.balance += self.amount
            self.account.save()


class RegularTransaction(models.Model):
    DAY = 'День'
    WEEK = 'Неделя'
    MONTH = 'Месяц'
    YEAR = 'Год'
    PERIODICITY_CHOICES = (
        (DAY, 'День'),
        (WEEK, 'Неделя'),
        (MONTH, 'Месяц'),
        (YEAR, 'Год'),
    )

    EXPENSES = 'Расходы'
    INCOME = 'Доходы'
    CATEGORY_TYPE_CHOICES = (
        (EXPENSES, 'Расходы'),
        (INCOME, 'Доходы'),
    )

    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    key = models.CharField(max_length=100, choices=CATEGORY_TYPE_CHOICES, default=EXPENSES, blank=True)
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[positive_number_validator])
    date = models.DateField()
    periodicity = models.CharField(max_length=10, choices=PERIODICITY_CHOICES, default=DAY)
    time_of_notification = models.TimeField()
    comment = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.key}, {self.category}, {self.amount}, " \
               f"{self.account}, {self.date}, {self.comment}"

    def save(self, *args, **kwargs):
        if self.key == RegularTransaction.EXPENSES and self.amount > self.account.balance:
            raise ValidationError("Сумма расхода превышает баланс счета.")

        super().save(*args, **kwargs)

        if self.key == RegularTransaction.EXPENSES:
            self.account.balance -= self.amount
            self.account.save()

        elif self.key == RegularTransaction.INCOME:
            self.account.balance += self.amount
            self.account.save()


def create_default_categories(sender, instance, created, **kwargs):
    if created:
        if CategoryModel.objects.filter(user=instance).count() == 0:
            default_categories_expenses = [
                {'name': 'Кафе и рестораны', 'color': '#abc270'},
                {'name': 'Одежда и аксессуары', 'color': '#c2a170'},
                {'name': 'Красота и здоровье', 'color': '#8fa1b1'},
                {'name': 'Продукты', 'color': '#b74dac'},
                {'name': 'Все для дома', 'color': '#2b2988'},
                {'name': 'Транспорт', 'color': '#5e876c'},
                {'name': 'Развлечения', 'color': '#7a0c0c'},
                {'name': 'Обязательные платежи', 'color': '#bee12f'},
                {'name': 'Переводы', 'color': '#fda769'},
                {'name': 'Другое', 'color': '#bb73dc'}
            ]
            default_categories_revenues = [
                {'name': 'Зарплата', 'color': '#abc270'},
                {'name': 'Стипендия', 'color': '#c2a170'},
                {'name': 'Социальные выплаты', 'color': '#8fa1b1'},
                {'name': 'Проценты по вкладу', 'color': '#fda769'},
                {'name': 'Переводы', 'color': '#5e047d'},
                {'name': 'Другое', 'color': '#313f42'}
            ]

            for category_data in default_categories_expenses:
                category = CategoryModel(user=instance,
                                         category_name=category_data['name'],
                                         key='Расходы',
                                         color=category_data['color'])
                category.save()

            for category_data in default_categories_revenues:
                category = CategoryModel(user=instance,
                                         category_name=category_data['name'],
                                         key='Доходы',
                                         color=category_data['color'])
                category.save()


post_save.connect(create_default_categories, sender=AUTH_USER_MODEL)

BudgetAnalysisWeb/users/forms.py
import accounts as accounts
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm,
    AuthenticationForm as DjangoAuthenticationForm,
)
from django import forms
from django.core.exceptions import ValidationError
from django.forms import Select, TimeInput, DateInput
from django.utils.translation import gettext_lazy as _

from users.models import UserDataModel, CategoryModel, Account, Transaction, Operation, RegularTransaction
from users.utils import send_email_for_verify

User = get_user_model()


class AuthenticationForm(DjangoAuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)

            if not self.user_cache.email_verify:
                send_email_for_verify(self.request, self.user_cache)
                raise ValidationError('Ваш почта не верифицирована, проверьте ее', code='invalid_login')

            if self.user_cache is None:
                raise self.get_invalid_login_error()

            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class UserCreationFormImpl(DjangoUserCreationForm):

    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

    class Meta(DjangoUserCreationForm.Meta):
        model = User
        fields = ('username', 'email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserDataModel
        fields = ('name', 'surname', 'patronymic', 'date_of_birth', 'phone', 'sex')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        user_profile = super().save(commit=False)
        if self.request and self.request.user:
            user_profile.user = self.request.user
        if commit:
            user_profile.save()
        return user_profile


class CategoryForm(forms.ModelForm):
    class Meta:
        model = CategoryModel
        fields = ('category_name', 'key', 'color')
        widgets = {
            'color': forms.TextInput(attrs={'type': 'color'}),
        }


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'balance', 'color']
        widgets = {
            'color': forms.TextInput(attrs={'type': 'color'}),
        }


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['from_account', 'to_account', 'amount', 'date', 'comment']

        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }


class OperationForm(forms.ModelForm):
    class Meta:
        model = Operation
        fields = ['key', 'category', 'account', 'date', 'amount', 'comment']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-select'}),
            'account': forms.Select(attrs={'class': 'form-select'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'min': '0'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }

    def __init__(self, user, *args, **kwargs):
        super(OperationForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = CategoryModel.objects.filter(user=user)
        self.fields['account'].queryset = Account.objects.filter(user=user)


class RegularTransactionForm(forms.ModelForm):
    class Meta:
        model = RegularTransaction
        fields = ['key', 'category', 'amount', 'account', 'date', 'periodicity', 'time_of_notification', 'comment']
        widgets = {
            'category': Select(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'account': Select(attrs={'class': 'form-control'}),
            'date': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'periodicity': Select(attrs={'class': 'form-control'}),
            'time_of_notification': TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'comment': forms.TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = CategoryModel.objects.filter(user=user)
        self.fields['account'].queryset = Account.objects.filter(user=user)


class OperationFilterForm(forms.Form):
    account = forms.ModelChoiceField(queryset=Account.objects.none(), required=False, empty_label="Все счета",)
    period = forms.ChoiceField(choices=RegularTransaction.PERIODICITY_CHOICES)
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['account'].queryset = Account.objects.filter(user=user)


class OperationFilterForStatisticForm(forms.Form):
    account = forms.ModelChoiceField(queryset=Account.objects.none(), required=False, empty_label="Все счета",)
    period = forms.ChoiceField(choices=RegularTransaction.PERIODICITY_CHOICES)
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['account'].queryset = Account.objects.filter(user=user)

BudgetAnalysisWeb/users/templates/users/profile/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styleUserProfile.css' %}">
  {% block title %}
  {% endblock %}
</head>
<body>
  <header>
    <div id="title"><h1>SmartMoney</h1></div>
    <div class="column-profile-notifications">
      <div class="search">
        <h3>
          <form action="" method="get">
            <input class="name-search" name="search" placeholder="Поиск" type="search">
            <input type="image" src="/static/images/search-image.png" class="button-search" name="submit">
          </form>
        </h3>
        <div class="search-line"></div>
      </div>
      <div class="noti-profile">
        <div class="notification-list">
          <img class="notification-image"  src="/static/images/notification-image.png"/>
        </div>
        <div class="profile-list">
          <a href="{% url 'profile' %}">
            <img class="profile-image" src="/static/images/ava.png"/>
          </a>
        </div>
      </div>
    </div>
  </header>

  {% block content %}
  {% endblock %}


    <footer>
    <div class="footer">
      <div class="footer-title">
        <a href="{% url 'main' %}" class="home-link">SmartMoney</a>
      </div>

        <ul class="list-menu-footer">
          <li>
            <a class="nav-link" href="{% url 'main' %}">Главная</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts' %}">Счета</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'statistics' %}">Статистика</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
          </li>
          <li>
            <a class="nav-link" href="#">Настройки</a>
          </li>
          <li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </li>
        </ul>
      <ul class="feedback">
        <li>Если появились вопросы, свяжитесь с нами</li>
        <li>E-mail: ratshackers@mail.ru</li>
      </ul>
    </div>
  </footer>
    {% block footer %}
  {% endblock %}

</body>
</html>

BudgetAnalysisWeb/users/templates/users/profile/categories.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/styleCategory.css' %}">
    <title>Категории</title>
</head>
<body>



<footer>
    <div class="footer">
      <div class="footer-title">
        <a href="{% url 'main' %}" class="home-link">SmartMoney</a>
      </div>
        <ul class="list-menu-footer">
          <li>
            <a class="nav-link" href="{% url 'main' %}">Главная</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts' %}">Счета</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'statistics' %}">Статистика</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
          </li>
          <li>
            <a class="nav-link" href="#">Настройки</a>
          </li>
          <li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </li>
        </ul>
      <ul class="feedback">
        <li>Если появились вопросы, свяжитесь с нами</li>
        <li>E-mail: ratshackers@mail.ru</li>
      </ul>
    </div>
  </footer>

</body>
</html>

BudgetAnalysisWeb/users/templates/users/profile/profile.html
{% extends 'users/profile/base.html' %}

{% block title %}
{% endblock %}

{% block content %}

<div class="container">
  <div class="user-info">
      <div class="avatar">
        <img class="avatar-image" src="/static/images/ava.png"/>
      </div>
      <div class="user-name">
        <form>
          <h2>{{ form.name }} {{ form.surname }}</h2>
        </form>
      </div>
  </div>

  <form method="post">
    {% csrf_token %}
      <div id="profile-form">
        <div class="content-form">
          <div class="profile-form">
            <div class="row">
              <div class="row-item-one">
                <div class="row-item-one-left">
                  <label>Email</label>
                  <input type="text"
                         class="login"
                         required placeholder="{{ user }}" readonly>
                </div>
                <div class="row-item-two-left">
                  <label for="id_name">Имя</label>
                  <input name="name"
                         id="id_name"
                         type="text"
                         class="name"
                         required placeholder="Имя"
                         value="{{ form.name.value }}">
                </div>
                <div class="row-item-three-left">
                  <label for="id_surname">Фамилия</label>
                  <input name="surname"
                         id="id_surname"
                         type="text"
                         class="surname"
                         required placeholder="Фамилия"
                         value="{{ form.surname.value }}">
                </div>
                <div class="row-item-four-left">
                  <label for="id_surname">Отчество</label>
                  <input name="patronymic"
                         id="id_patronymic"
                         type="text"
                         class="patronymic"
                         placeholder="Отчество"
                         value="{{ form.patronymic.value }}">
                </div>
              </div>
              <div class="row-item-two">
                <div class="row-item-one-right">
                  <label>Логин</label>
                  <input type="text" class="login" required placeholder={{ user.username }} readonly>
                </div>
                <div class="row-item-two-right">
                  <label for="id_date_of_birth">Дата рождения</label>
                  <input name="date_of_birth"
                         id="id_date_of_birth"
                         type="date"
                         class="birthdate"
                         placeholder="{{ form.date_of_birth.label }}"
                         value="{{ form.date_of_birth.value|date:'Y-m-d' }}">
                </div>
                <div class="row-item-three-right">
                  <label for="id_phone">Телефон</label>
                  <input name="phone"
                         id="id_phone"
                         type="text"
                         class="phone"
                         placeholder="Пример: +78005353535"
                         value="{{ form.phone.value }}">
                </div>
                <div class="row-item-four-right">
                  <label for="id_sex">Пол</label>
                  <input name="sex"
                         id="id_sex"
                         type="text"
                         class="sex"
                         placeholder="Мужской/Женский"
                         value="{{ form.sex.value }}">
                </div>
              </div>
            </div>
            <div class="btn"><button class="button-red" type="submit"><a>Сохранить</a></button></div>
          </div>
        </div>
      </div>
    </form>
  </div>


  {% block footer %}
    <footer>
    <div class="footer">
      <div class="footer-title">
        <a href="{% url 'main' %}" class="home-link">SmartMoney</a>
      </div>

        <ul class="list-menu-footer">
          <li>
            <a class="nav-link" href="{% url 'main' %}">Главная</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts' %}">Счета</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'statistics' %}">Статистика</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
          </li>
          <li>
            <a class="nav-link" href="#">Настройки</a>
          </li>
          <li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </li>
        </ul>
      <ul class="feedback">
        <li>Если появились вопросы, свяжитесь с нами</li>
        <li>E-mail: ratshackers@mail.ru</li>
      </ul>
    </div>
  </footer>
  {% endblock %}

{% endblock %}